// Configurations
export const FETCH_CONFIGURATIONS = 'FETCH_CONFIGURATIONS';
export const FETCH_CONFIGURATIONS_DONE = 'FETCH_CONFIGURATIONS_DONE';
export const FETCH_CONFIGURATIONS_FAILED = 'FETCH_CONFIGURATIONS_FAILED';


// Orders
export const CREATE_ORDER = 'CREATE_ORDER';
export const CREATE_ORDER_DONE = 'CREATE_ORDER_DONE';
export const CREATE_ORDER_FAILED = 'CREATE_ORDER_FAILED';

// Order Informations
export const SET_TOTALAMOUNT = 'SET_TOTAL_AMOUNT';
export const SET_GIVENNAME = 'SET_GIVEN_NAME';
export const SET_SURNAME = 'SET_SURNAME';
export const SET_EMAIL = 'SET_EMAIL';
export const SET_REDIRECTCONFIRMURL = 'SET_REDIRECTCONFIRMURL';
export const SET_REDIRECTCANCELMURL = 'SET_REDIRECTCANCELMURL';